name: Run Unit Test via Pytest

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      # - name: Lint with Ruff
      #   run: |
      #     pip install ruff
      #     ruff --format=github --target-version=py310 .
      #   continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest  -v -s
      - name: Generate Coverage Report and Badge
        run: |
          coverage report -m
          coverage-badge -o coverage.svg
          mkdir -p public
          mv coverage.svg public/ 
      - name: Deploy badge to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./operation_safe_passage/public